package com.learnlogic.ecommerce.merabazar.model;

// Generated May 31, 2015 3:00:15 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.learnlogic.ecommerce.merabazar.model.Products;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "merabazar")
public class Category implements java.io.Serializable {

	private long categoryId;
	private Products products;
	private String categoryName;
	private String categoryDesc;
	private byte[] categoryImage;
	private String active;
	private Set productses = new HashSet(0);

	public Category() {
	}

	public Category(long categoryId) {
		this.categoryId = categoryId;
	}

	public Category(long categoryId, Products products, String categoryName,
			String categoryDesc, byte[] categoryImage, String active,
			Set productses) {
		this.categoryId = categoryId;
		this.products = products;
		this.categoryName = categoryName;
		this.categoryDesc = categoryDesc;
		this.categoryImage = categoryImage;
		this.active = active;
		this.productses = productses;
	}

	@Id
	@Column(name = "category_id", unique = true, nullable = false)
	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prodid")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "category_name", length = 45)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "category_desc", length = 320)
	public String getCategoryDesc() {
		return this.categoryDesc;
	}

	public void setCategoryDesc(String categoryDesc) {
		this.categoryDesc = categoryDesc;
	}

	@Column(name = "category_image")
	public byte[] getCategoryImage() {
		return this.categoryImage;
	}

	public void setCategoryImage(byte[] categoryImage) {
		this.categoryImage = categoryImage;
	}

	@Column(name = "active", length = 45)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set getProductses() {
		return this.productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}

}
