package com.learnlogic.ecommerce.merabazar.model;

// Generated May 31, 2015 3:00:15 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "feedback", catalog = "merabazar")
public class Feedback implements java.io.Serializable {

	private long feedbackId;
	private String feedbackDesc;
	private Long userId;
	private Long productId;
	private Long supplierId;

	public Feedback() {
	}

	public Feedback(long feedbackId) {
		this.feedbackId = feedbackId;
	}

	public Feedback(long feedbackId, String feedbackDesc, Long userId,
			Long productId, Long supplierId) {
		this.feedbackId = feedbackId;
		this.feedbackDesc = feedbackDesc;
		this.userId = userId;
		this.productId = productId;
		this.supplierId = supplierId;
	}

	@Id
	@Column(name = "Feedback_id", unique = true, nullable = false)
	public long getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(long feedbackId) {
		this.feedbackId = feedbackId;
	}

	@Column(name = "Feedback_desc", length = 450)
	public String getFeedbackDesc() {
		return this.feedbackDesc;
	}

	public void setFeedbackDesc(String feedbackDesc) {
		this.feedbackDesc = feedbackDesc;
	}

	@Column(name = "UserID")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "ProductID")
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name = "SupplierID")
	public Long getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Long supplierId) {
		this.supplierId = supplierId;
	}

}
