package com.learnlogic.ecommerce.merabazar.model;

// Generated May 31, 2015 3:00:15 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "merabazar")
public class Orders implements java.io.Serializable {

	private long orderId;
	private Users users;
	private Shipping shipping;
	private Payment payment;
	private long ordernumber;
	private Date orderDate;
	private Date shipDate;
	private String orderAmount;
	private String orderTrackingnumber;
	private Long orderTax;
	private String orderShipaddress1;
	private String orderShipaddress2;
	private String orderCity;
	private String orderState;
	private String orderZip;
	private Date orderPaymentDate;
	private Set userses = new HashSet(0);
	private Set orderDetails = new HashSet(0);

	public Orders() {
	}

	public Orders(long orderId, Users users, Payment payment, long ordernumber) {
		this.orderId = orderId;
		this.users = users;
		this.payment = payment;
		this.ordernumber = ordernumber;
	}

	public Orders(long orderId, Users users, Shipping shipping,
			Payment payment, long ordernumber, Date orderDate, Date shipDate,
			String orderAmount, String orderTrackingnumber, Long orderTax,
			String orderShipaddress1, String orderShipaddress2,
			String orderCity, String orderState, String orderZip,
			Date orderPaymentDate, Set userses, Set orderDetails) {
		this.orderId = orderId;
		this.users = users;
		this.shipping = shipping;
		this.payment = payment;
		this.ordernumber = ordernumber;
		this.orderDate = orderDate;
		this.shipDate = shipDate;
		this.orderAmount = orderAmount;
		this.orderTrackingnumber = orderTrackingnumber;
		this.orderTax = orderTax;
		this.orderShipaddress1 = orderShipaddress1;
		this.orderShipaddress2 = orderShipaddress2;
		this.orderCity = orderCity;
		this.orderState = orderState;
		this.orderZip = orderZip;
		this.orderPaymentDate = orderPaymentDate;
		this.userses = userses;
		this.orderDetails = orderDetails;
	}

	@Id
	@Column(name = "Order_id", unique = true, nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Usersid", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ship_Id")
	public Shipping getShipping() {
		return this.shipping;
	}

	public void setShipping(Shipping shipping) {
		this.shipping = shipping;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Payment_id", nullable = false)
	public Payment getPayment() {
		return this.payment;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}

	@Column(name = "Ordernumber", nullable = false)
	public long getOrdernumber() {
		return this.ordernumber;
	}

	public void setOrdernumber(long ordernumber) {
		this.ordernumber = ordernumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Order_date", length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Ship_date", length = 19)
	public Date getShipDate() {
		return this.shipDate;
	}

	public void setShipDate(Date shipDate) {
		this.shipDate = shipDate;
	}

	@Column(name = "Order_amount", length = 45)
	public String getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(String orderAmount) {
		this.orderAmount = orderAmount;
	}

	@Column(name = "Order_trackingnumber", length = 45)
	public String getOrderTrackingnumber() {
		return this.orderTrackingnumber;
	}

	public void setOrderTrackingnumber(String orderTrackingnumber) {
		this.orderTrackingnumber = orderTrackingnumber;
	}

	@Column(name = "Order_Tax")
	public Long getOrderTax() {
		return this.orderTax;
	}

	public void setOrderTax(Long orderTax) {
		this.orderTax = orderTax;
	}

	@Column(name = "Order_Shipaddress1", length = 45)
	public String getOrderShipaddress1() {
		return this.orderShipaddress1;
	}

	public void setOrderShipaddress1(String orderShipaddress1) {
		this.orderShipaddress1 = orderShipaddress1;
	}

	@Column(name = "Order_shipaddress2", length = 45)
	public String getOrderShipaddress2() {
		return this.orderShipaddress2;
	}

	public void setOrderShipaddress2(String orderShipaddress2) {
		this.orderShipaddress2 = orderShipaddress2;
	}

	@Column(name = "Order_city", length = 45)
	public String getOrderCity() {
		return this.orderCity;
	}

	public void setOrderCity(String orderCity) {
		this.orderCity = orderCity;
	}

	@Column(name = "Order_state", length = 45)
	public String getOrderState() {
		return this.orderState;
	}

	public void setOrderState(String orderState) {
		this.orderState = orderState;
	}

	@Column(name = "Order_Zip", length = 45)
	public String getOrderZip() {
		return this.orderZip;
	}

	public void setOrderZip(String orderZip) {
		this.orderZip = orderZip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Order_payment_Date", length = 19)
	public Date getOrderPaymentDate() {
		return this.orderPaymentDate;
	}

	public void setOrderPaymentDate(Date orderPaymentDate) {
		this.orderPaymentDate = orderPaymentDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}

}
