package com.learnlogic.ecommerce.merabazar.model;

// Generated May 31, 2015 3:00:15 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail", catalog = "merabazar")
public class OrderDetail implements java.io.Serializable {

	private long detailId;
	private Orders orders;
	private Products products;
	private String detailName;
	private String detailPrice;
	private String detailSkU;
	private String detailQuantity;
	private String discount;
	private String detailOrderNumber;
	private Set shoppingcarts = new HashSet(0);

	public OrderDetail() {
	}

	public OrderDetail(long detailId, Orders orders, Products products) {
		this.detailId = detailId;
		this.orders = orders;
		this.products = products;
	}

	public OrderDetail(long detailId, Orders orders, Products products,
			String detailName, String detailPrice, String detailSkU,
			String detailQuantity, String discount, String detailOrderNumber,
			Set shoppingcarts) {
		this.detailId = detailId;
		this.orders = orders;
		this.products = products;
		this.detailName = detailName;
		this.detailPrice = detailPrice;
		this.detailSkU = detailSkU;
		this.detailQuantity = detailQuantity;
		this.discount = discount;
		this.detailOrderNumber = detailOrderNumber;
		this.shoppingcarts = shoppingcarts;
	}

	@Id
	@Column(name = "detail_id", unique = true, nullable = false)
	public long getDetailId() {
		return this.detailId;
	}

	public void setDetailId(long detailId) {
		this.detailId = detailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "detail_order_id", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "detail_product_id", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "detail_name", length = 200)
	public String getDetailName() {
		return this.detailName;
	}

	public void setDetailName(String detailName) {
		this.detailName = detailName;
	}

	@Column(name = "detail_price", length = 45)
	public String getDetailPrice() {
		return this.detailPrice;
	}

	public void setDetailPrice(String detailPrice) {
		this.detailPrice = detailPrice;
	}

	@Column(name = "detail_skU", length = 45)
	public String getDetailSkU() {
		return this.detailSkU;
	}

	public void setDetailSkU(String detailSkU) {
		this.detailSkU = detailSkU;
	}

	@Column(name = "detail_quantity", length = 45)
	public String getDetailQuantity() {
		return this.detailQuantity;
	}

	public void setDetailQuantity(String detailQuantity) {
		this.detailQuantity = detailQuantity;
	}

	@Column(name = "discount", length = 45)
	public String getDiscount() {
		return this.discount;
	}

	public void setDiscount(String discount) {
		this.discount = discount;
	}

	@Column(name = "detail_order_number", length = 45)
	public String getDetailOrderNumber() {
		return this.detailOrderNumber;
	}

	public void setDetailOrderNumber(String detailOrderNumber) {
		this.detailOrderNumber = detailOrderNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderDetail")
	public Set getShoppingcarts() {
		return this.shoppingcarts;
	}

	public void setShoppingcarts(Set shoppingcarts) {
		this.shoppingcarts = shoppingcarts;
	}

}
