package com.learnlogic.ecommerce.merabazar.model;

// Generated May 31, 2015 3:00:15 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "merabazar")
public class Payment implements java.io.Serializable {

	private long paymentId;
	private String paymentType;
	private String allowed;
	private Set orderses = new HashSet(0);

	public Payment() {
	}

	public Payment(long paymentId) {
		this.paymentId = paymentId;
	}

	public Payment(long paymentId, String paymentType, String allowed,
			Set orderses) {
		this.paymentId = paymentId;
		this.paymentType = paymentType;
		this.allowed = allowed;
		this.orderses = orderses;
	}

	@Id
	@Column(name = "paymentId", unique = true, nullable = false)
	public long getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(long paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "payment_type", length = 45)
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "allowed", length = 11)
	public String getAllowed() {
		return this.allowed;
	}

	public void setAllowed(String allowed) {
		this.allowed = allowed;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "payment")
	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
