package com.learnlogic.ecommerce.merabazar.model;

// Generated May 31, 2015 3:00:15 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products", catalog = "merabazar")
public class Products implements java.io.Serializable {

	private long productId;
	private Category category;
	private Suppliers suppliers;
	private String productName;
	private String productSku;
	private Float productPrice;
	private String productDescription;
	private byte[] productImage;
	private String productLongDesc;
	private String productSize;
	private String productColor;
	private String productAvailableSize;
	private String productAvailableColor;
	private String productDiscount;
	private String note;
	private Set supplierses = new HashSet(0);
	private Set shoppingcarts = new HashSet(0);
	private Set categories = new HashSet(0);
	private Set orderDetails = new HashSet(0);

	public Products() {
	}

	public Products(long productId, String productName) {
		this.productId = productId;
		this.productName = productName;
	}

	public Products(long productId, Category category, Suppliers suppliers,
			String productName, String productSku, Float productPrice,
			String productDescription, byte[] productImage,
			String productLongDesc, String productSize, String productColor,
			String productAvailableSize, String productAvailableColor,
			String productDiscount, String note, Set supplierses,
			Set shoppingcarts, Set categories, Set orderDetails) {
		this.productId = productId;
		this.category = category;
		this.suppliers = suppliers;
		this.productName = productName;
		this.productSku = productSku;
		this.productPrice = productPrice;
		this.productDescription = productDescription;
		this.productImage = productImage;
		this.productLongDesc = productLongDesc;
		this.productSize = productSize;
		this.productColor = productColor;
		this.productAvailableSize = productAvailableSize;
		this.productAvailableColor = productAvailableColor;
		this.productDiscount = productDiscount;
		this.note = note;
		this.supplierses = supplierses;
		this.shoppingcarts = shoppingcarts;
		this.categories = categories;
		this.orderDetails = orderDetails;
	}

	@Id
	@Column(name = "Product_id", unique = true, nullable = false)
	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cat_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SupplierId")
	public Suppliers getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Suppliers suppliers) {
		this.suppliers = suppliers;
	}

	@Column(name = "Product_name", nullable = false, length = 40)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "Product_sku", length = 45)
	public String getProductSku() {
		return this.productSku;
	}

	public void setProductSku(String productSku) {
		this.productSku = productSku;
	}

	@Column(name = "Product_price", precision = 12, scale = 0)
	public Float getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(Float productPrice) {
		this.productPrice = productPrice;
	}

	@Column(name = "Product_description", length = 200)
	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	@Column(name = "Product_image")
	public byte[] getProductImage() {
		return this.productImage;
	}

	public void setProductImage(byte[] productImage) {
		this.productImage = productImage;
	}

	@Column(name = "Product_longDesc", length = 65535)
	public String getProductLongDesc() {
		return this.productLongDesc;
	}

	public void setProductLongDesc(String productLongDesc) {
		this.productLongDesc = productLongDesc;
	}

	@Column(name = "Product_size", length = 45)
	public String getProductSize() {
		return this.productSize;
	}

	public void setProductSize(String productSize) {
		this.productSize = productSize;
	}

	@Column(name = "Product_color", length = 45)
	public String getProductColor() {
		return this.productColor;
	}

	public void setProductColor(String productColor) {
		this.productColor = productColor;
	}

	@Column(name = "Product_available_size", length = 45)
	public String getProductAvailableSize() {
		return this.productAvailableSize;
	}

	public void setProductAvailableSize(String productAvailableSize) {
		this.productAvailableSize = productAvailableSize;
	}

	@Column(name = "Product_available_color", length = 45)
	public String getProductAvailableColor() {
		return this.productAvailableColor;
	}

	public void setProductAvailableColor(String productAvailableColor) {
		this.productAvailableColor = productAvailableColor;
	}

	@Column(name = "Product_discount", length = 45)
	public String getProductDiscount() {
		return this.productDiscount;
	}

	public void setProductDiscount(String productDiscount) {
		this.productDiscount = productDiscount;
	}

	@Column(name = "Note", length = 45)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set getSupplierses() {
		return this.supplierses;
	}

	public void setSupplierses(Set supplierses) {
		this.supplierses = supplierses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set getShoppingcarts() {
		return this.shoppingcarts;
	}

	public void setShoppingcarts(Set shoppingcarts) {
		this.shoppingcarts = shoppingcarts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set getCategories() {
		return this.categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}

}
