package com.learnlogic.ecommerce.merabazar.model;

// Generated May 31, 2015 3:00:15 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shipping generated by hbm2java
 */
@Entity
@Table(name = "shipping", catalog = "merabazar")
public class Shipping implements java.io.Serializable {

	private long shippingId;
	private String shippingCompany;
	private String shuppingDetail;
	private Set orderses = new HashSet(0);

	public Shipping() {
	}

	public Shipping(long shippingId) {
		this.shippingId = shippingId;
	}

	public Shipping(long shippingId, String shippingCompany,
			String shuppingDetail, Set orderses) {
		this.shippingId = shippingId;
		this.shippingCompany = shippingCompany;
		this.shuppingDetail = shuppingDetail;
		this.orderses = orderses;
	}

	@Id
	@Column(name = "Shipping_id", unique = true, nullable = false)
	public long getShippingId() {
		return this.shippingId;
	}

	public void setShippingId(long shippingId) {
		this.shippingId = shippingId;
	}

	@Column(name = "Shipping_company", length = 45)
	public String getShippingCompany() {
		return this.shippingCompany;
	}

	public void setShippingCompany(String shippingCompany) {
		this.shippingCompany = shippingCompany;
	}

	@Column(name = "Shupping_detail", length = 100)
	public String getShuppingDetail() {
		return this.shuppingDetail;
	}

	public void setShuppingDetail(String shuppingDetail) {
		this.shuppingDetail = shuppingDetail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shipping")
	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
