package com.learnlogic.ecommerce.merabazar.model;

// Generated May 31, 2015 3:00:15 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Shoppingcart generated by hbm2java
 */
@Entity
@Table(name = "shoppingcart", catalog = "merabazar")
public class Shoppingcart implements java.io.Serializable {

	private long shoppingcartId;
	private Products products;
	private OrderDetail orderDetail;
	private Users users;
	private String desc;

	public Shoppingcart() {
	}

	public Shoppingcart(long shoppingcartId) {
		this.shoppingcartId = shoppingcartId;
	}

	public Shoppingcart(long shoppingcartId, Products products,
			OrderDetail orderDetail, Users users, String desc) {
		this.shoppingcartId = shoppingcartId;
		this.products = products;
		this.orderDetail = orderDetail;
		this.users = users;
		this.desc = desc;
	}

	@Id
	@Column(name = "shoppingcart_id", unique = true, nullable = false)
	public long getShoppingcartId() {
		return this.shoppingcartId;
	}

	public void setShoppingcartId(long shoppingcartId) {
		this.shoppingcartId = shoppingcartId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productid")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "detailid")
	public OrderDetail getOrderDetail() {
		return this.orderDetail;
	}

	public void setOrderDetail(OrderDetail orderDetail) {
		this.orderDetail = orderDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "desc", length = 450)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}
