package com.learnlogic.ecommerce.merabazar.model;

// Generated May 31, 2015 3:00:15 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Suppliers generated by hbm2java
 */
@Entity
@Table(name = "suppliers", catalog = "merabazar")
public class Suppliers implements java.io.Serializable {

	private long supplierId;
	private Products products;
	private String companyName;
	private String contactFname;
	private String contactLname;
	private String contactTitle;
	private String city;
	private String state;
	private String zipcode;
	private String country;
	private String phone;
	private String email;
	private String url;
	private String paymentMethod;
	private String discountAvailable;
	private Set productses = new HashSet(0);

	public Suppliers() {
	}

	public Suppliers(long supplierId) {
		this.supplierId = supplierId;
	}

	public Suppliers(long supplierId, Products products, String companyName,
			String contactFname, String contactLname, String contactTitle,
			String city, String state, String zipcode, String country,
			String phone, String email, String url, String paymentMethod,
			String discountAvailable, Set productses) {
		this.supplierId = supplierId;
		this.products = products;
		this.companyName = companyName;
		this.contactFname = contactFname;
		this.contactLname = contactLname;
		this.contactTitle = contactTitle;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.country = country;
		this.phone = phone;
		this.email = email;
		this.url = url;
		this.paymentMethod = paymentMethod;
		this.discountAvailable = discountAvailable;
		this.productses = productses;
	}

	@Id
	@Column(name = "Supplier_id", unique = true, nullable = false)
	public long getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(long supplierId) {
		this.supplierId = supplierId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Productsid")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "Company_name", length = 45)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "Contact_fname", length = 45)
	public String getContactFname() {
		return this.contactFname;
	}

	public void setContactFname(String contactFname) {
		this.contactFname = contactFname;
	}

	@Column(name = "Contact_lname", length = 45)
	public String getContactLname() {
		return this.contactLname;
	}

	public void setContactLname(String contactLname) {
		this.contactLname = contactLname;
	}

	@Column(name = "Contact_title", length = 45)
	public String getContactTitle() {
		return this.contactTitle;
	}

	public void setContactTitle(String contactTitle) {
		this.contactTitle = contactTitle;
	}

	@Column(name = "City", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "State", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zipcode", length = 45)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "URL", length = 45)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "payment_method", length = 45)
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "Discount_available", length = 50)
	public String getDiscountAvailable() {
		return this.discountAvailable;
	}

	public void setDiscountAvailable(String discountAvailable) {
		this.discountAvailable = discountAvailable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "suppliers")
	public Set getProductses() {
		return this.productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}

}
